close all;
clear all;
disp('-------------------------------------------------------------------');
disp('M. S. Grewal and A. P. Andrews');
disp('Kalman Filtering Theory and Practice Using MATLAB, 4th Edition,');
disp('Wiley, 2014');
disp('Chapter 8');
disp('-------------------------------------------------------------------');
disp('Example 8.11 and Figure 8.21');
disp('Compare Extended Kalman Filter (EKF) and Unscented Kalman Filter (UKF)');
disp('nonlinear variance approximations, using atan(a*X) X in N(0,1),');
disp('and varying the scaling parameter a.');
disp('-------------------------------------------------------------------');
tic;
N       = 10^5;
disp(['Equiprobability partitioning into ',num2str(N),' segments.']);
x       = GaussEqPart(N);
disp(['Equiprobability partitioning completed.']);
disp([num2str(min(x)),' < x < ',num2str(max(x))]);
toc;pause(1);
disp(['Calculate EKF, UKF and numerical covariances.']);
log10a   = [-6:.1:6];
for n=1:length(log10a),
    a(n)        = 10^log10a(n);
    sigsqUKF(n) = (atan(a(n)))^2;
    sigsqEKF(n) = a(n)^2;
    for k=1:length(x);
        f(k)    = atan(a(n)*x(k));
        fsq(k)  = f(k)^2;
    end;
    sigmasq(n)  = sum(fsq)/N;
end;
disp('EKF, UKF and numerical covariances calculated.');
toc;pause(1);
disp('Plot results.');
figure;
loglog(a,sigmasq,'k-',a,sigsqUKF,'k--',a,sigsqEKF,'k-.','LineWidth',1.5);
xlabel('a','FontSize',18);
ylabel('ESTIMATED {\sigma}^2 OF arctan(ax)','FontSize',18);
legend('NUM','UKF','EKF');
title([num2str(N),' SAMPLES OF GAUSSIAN DISTRIBUTION'],'FontSize',16);
relerr = [(sigsqEKF - sigmasq)./sigmasq;(sigsqUKF - sigmasq)./sigmasq];
figure;
loglog(a,relerr(1,:),'k-.',a,relerr(2,:),'k--','LineWidth',1.5);
xlabel('a','FontSize',18);
ylabel('REL. EST. ERR. IN {\sigma}^2 OF arctan(ax)','FontSize',18);
legend('EKF','UKF');
title([num2str(N),' SAMPLES OF GAUSSIAN DISTRIBUTION'],'FontSize',16);
disp('Plotting completed.');
toc;
disp('-------------------------------------------------------------------');
disp('Second plot should look like Figure 8.21, showing both methods');
disp('getting worse as a increases, but relative UKF error peaking at around');
disp('43%, but relative EKF error increasing without bound.');
disp('-------------------------------------------------------------------');